name: repo-sync
on: [push]

jobs:
  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - shell: bash
      run: |
         curl -L https://dl.google.com/android/repository/android-ndk-r20-${{ runner.os }}-x86_64.zip | unzip -
  test2:
    name: Test with bb
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - shell: bash
      run: |
         curl -L https://dl.google.com/android/repository/android-ndk-r20-${{ runner.os }}-x86_64.zip | busybox unzip -
