name: repo-sync
on: [push]

jobs:
  Multiline_fail:
    name: Multiline fail
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Hello
        false
        echo Goodbye
  Multiline_fail_in_pipe:
    name: Multiline fail in pipe
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Hello
        echo "test" | false | tee foobar
        echo Goodbye
  Multiline_fail_in_chain:
    name: Multiline fail in chain
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Hello
        mkdir test
        cd test && false && cd ..
        echo Goodbye
