name: repo-sync
on: [push]

jobs:
  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, mac-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - shell: bash
      run: |
          os=${{ runner.os }}
          file=android-ndk-r20-${os/macOS/darwin}-x86_64.zip
          curl -LO https://dl.google.com/android/repository/$file
          unzip $file
